//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let tl = _ModuleRegistry.module("tl");

    const iceC_tl_Printer_ids = [
        "::Ice::Object",
        "::tl::Printer"
    ];

    tl.Printer = class extends Ice.Object
    {
    };

    tl.PrinterPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(tl.Printer, tl.PrinterPrx, iceC_tl_Printer_ids, 1,
    {
        "printString": [, , , , , [[7]], , , , ]
    });
    exports.tl = tl;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
