//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `PlayerCommands.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package tl;

/** @hidden */
public class _PlayerCommandsPrxI extends com.zeroc.Ice._ObjectPrxI implements PlayerCommandsPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
