/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tl;

public class App {
    public static void main(String[] args) {
        StreamHttp streamHttp = new StreamHttp("/home/tom/Musique/french-lesson-numbers-1-100-compter-jusqua-100-learn-french.mp3" , "localhost", 5555);
        Thread t1 = new Thread(streamHttp);
        t1.start();

        try(com.zeroc.Ice.Communicator communicator = com.zeroc.Ice.Util.initialize(args))
        {
            com.zeroc.Ice.ObjectAdapter adapter = communicator.createObjectAdapterWithEndpoints("PlayerAdapter", "default -p 10000");
            com.zeroc.Ice.Object object = new Player(streamHttp);
            adapter.add(object, com.zeroc.Ice.Util.stringToIdentity("player"));
            adapter.activate();
            communicator.waitForShutdown();
        }
    }
}
