/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tl;

import com.zeroc.Ice.ObjectAdapter;
import com.zeroc.Ice.Object;
import com.zeroc.Ice.Communicator;
import com.zeroc.Ice.LocalException;
import com.zeroc.Ice.Util;

public class App {
    public static void main(String[] args) {
        StreamHttp streamHttp = new StreamHttp("localhost", 5555);
        Thread t1 = new Thread(streamHttp);
        t1.start();

        try(Communicator communicator = Util.initialize(args))
        {
            ObjectAdapter adapter = communicator.createObjectAdapterWithEndpoints("PlayerAdapter", "default -p 10000");
            Object object = new Player(streamHttp);
            adapter.add(object,Util.stringToIdentity("player"));
            adapter.activate();
            System.out.println("Player ready");
            communicator.waitForShutdown();
        } catch (LocalException e) {
            e.printStackTrace();
        }
    }
}
