/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tl;

import com.zeroc.Ice.*;
import com.zeroc.Ice.Object;

public class App {

    protected final static String FOLDER = "/home/tom/Project/Application-Architectures-distribuees/ICE/Server/app/src/main/resources/";

    public static void main(String[] args) {
        StreamHttp streamHttp = new StreamHttp("localhost", 5555);
        Thread t1 = new Thread(streamHttp);
        t1.start();

        try(Communicator communicator = Util.initialize(args))
        {
            Properties properties = communicator.getProperties();
            Object object = new Player(streamHttp);

            ObjectAdapter adapter = communicator.createObjectAdapter(properties.getProperty("PlayerAdapter.AdapterId")); //"default -p 10000"

            System.out.println(adapter.getEndpoints()[0]);

            adapter.add(object, Util.stringToIdentity("player"));
            adapter.activate();
            System.out.println("Player ready");
            communicator.waitForShutdown();
        } catch (LocalException e) {
            e.printStackTrace();
        }
    }
}
