//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `PlayerCommands.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package tl;

public interface PlayerCommandsPrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean play(boolean b)
    {
        return play(b, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean play(boolean b, java.util.Map<String, String> context)
    {
        return _iceI_playAsync(b, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> playAsync(boolean b)
    {
        return _iceI_playAsync(b, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> playAsync(boolean b, java.util.Map<String, String> context)
    {
        return _iceI_playAsync(b, context, false);
    }

    /**
     * @hidden
     * @param iceP_b -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_playAsync(boolean iceP_b, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "play", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeBool(iceP_b);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean playSong(String song)
    {
        return playSong(song, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean playSong(String song, java.util.Map<String, String> context)
    {
        return _iceI_playSongAsync(song, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> playSongAsync(String song)
    {
        return _iceI_playSongAsync(song, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> playSongAsync(String song, java.util.Map<String, String> context)
    {
        return _iceI_playSongAsync(song, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_playSongAsync(String iceP_song, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "playSong", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_song);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean stop()
    {
        return stop(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean stop(java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> stopAsync()
    {
        return _iceI_stopAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> stopAsync(java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_stopAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stop", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean repeat(boolean b)
    {
        return repeat(b, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean repeat(boolean b, java.util.Map<String, String> context)
    {
        return _iceI_repeatAsync(b, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> repeatAsync(boolean b)
    {
        return _iceI_repeatAsync(b, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> repeatAsync(boolean b, java.util.Map<String, String> context)
    {
        return _iceI_repeatAsync(b, context, false);
    }

    /**
     * @hidden
     * @param iceP_b -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_repeatAsync(boolean iceP_b, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "repeat", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeBool(iceP_b);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean volume(int b)
    {
        return volume(b, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean volume(int b, java.util.Map<String, String> context)
    {
        return _iceI_volumeAsync(b, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> volumeAsync(int b)
    {
        return _iceI_volumeAsync(b, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> volumeAsync(int b, java.util.Map<String, String> context)
    {
        return _iceI_volumeAsync(b, context, false);
    }

    /**
     * @hidden
     * @param iceP_b -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_volumeAsync(int iceP_b, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "volume", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_b);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default void downloadFile(String song)
    {
        downloadFile(song, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void downloadFile(String song, java.util.Map<String, String> context)
    {
        _iceI_downloadFileAsync(song, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> downloadFileAsync(String song)
    {
        return _iceI_downloadFileAsync(song, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> downloadFileAsync(String song, java.util.Map<String, String> context)
    {
        return _iceI_downloadFileAsync(song, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_downloadFileAsync(String iceP_song, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "downloadFile", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_song);
                 }, null);
        return f;
    }

    default void removeFile(String song)
    {
        removeFile(song, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void removeFile(String song, java.util.Map<String, String> context)
    {
        _iceI_removeFileAsync(song, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> removeFileAsync(String song)
    {
        return _iceI_removeFileAsync(song, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> removeFileAsync(String song, java.util.Map<String, String> context)
    {
        return _iceI_removeFileAsync(song, context, false);
    }

    /**
     * @hidden
     * @param iceP_song -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_removeFileAsync(String iceP_song, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "removeFile", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_song);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PlayerCommandsPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), PlayerCommandsPrx.class, _PlayerCommandsPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PlayerCommandsPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), PlayerCommandsPrx.class, _PlayerCommandsPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PlayerCommandsPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), PlayerCommandsPrx.class, _PlayerCommandsPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PlayerCommandsPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), PlayerCommandsPrx.class, _PlayerCommandsPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static PlayerCommandsPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, PlayerCommandsPrx.class, _PlayerCommandsPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static PlayerCommandsPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, PlayerCommandsPrx.class, _PlayerCommandsPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default PlayerCommandsPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (PlayerCommandsPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default PlayerCommandsPrx ice_adapterId(String newAdapterId)
    {
        return (PlayerCommandsPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default PlayerCommandsPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (PlayerCommandsPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default PlayerCommandsPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (PlayerCommandsPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default PlayerCommandsPrx ice_invocationTimeout(int newTimeout)
    {
        return (PlayerCommandsPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default PlayerCommandsPrx ice_connectionCached(boolean newCache)
    {
        return (PlayerCommandsPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default PlayerCommandsPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (PlayerCommandsPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PlayerCommandsPrx ice_secure(boolean b)
    {
        return (PlayerCommandsPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default PlayerCommandsPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (PlayerCommandsPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PlayerCommandsPrx ice_preferSecure(boolean b)
    {
        return (PlayerCommandsPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default PlayerCommandsPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (PlayerCommandsPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default PlayerCommandsPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (PlayerCommandsPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default PlayerCommandsPrx ice_collocationOptimized(boolean b)
    {
        return (PlayerCommandsPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default PlayerCommandsPrx ice_twoway()
    {
        return (PlayerCommandsPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default PlayerCommandsPrx ice_oneway()
    {
        return (PlayerCommandsPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default PlayerCommandsPrx ice_batchOneway()
    {
        return (PlayerCommandsPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default PlayerCommandsPrx ice_datagram()
    {
        return (PlayerCommandsPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default PlayerCommandsPrx ice_batchDatagram()
    {
        return (PlayerCommandsPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default PlayerCommandsPrx ice_compress(boolean co)
    {
        return (PlayerCommandsPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default PlayerCommandsPrx ice_timeout(int t)
    {
        return (PlayerCommandsPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default PlayerCommandsPrx ice_connectionId(String connectionId)
    {
        return (PlayerCommandsPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default PlayerCommandsPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (PlayerCommandsPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::tl::PlayerCommands";
    }
}
